#1
-
  html: envvars_block.html
  scenario: "NEXT"
  command: "#SETVARS"
  allowed_vars:
    KP_SELF_CERT: ""
    KP_WEB_DNS: "localhost"
    KP_WEB_MAIL: ""
  description: "Set environment vars"
-
  html: command_block.html
  scenario: "NEXT"
  command: env | grep "KP_"
  description: "Check KP_* envvars"
-
  html: save_to_xml.html
  scenario: "NEXT"
  command: "#XML"
  filepath: ../config.xml
  description: Edit kp_server configuration file
-
  html: save_to_xml_2.html
  scenario: "PART"
  command: "#XML"
  filepath: ../kportal_conf.xml
  description: "Edit kp_server configuration file kportal_conf.xml"

#5
-
  html: command_block.html
  scenario: "PART"
  command: ./disp.sh
  description: "Display test"
-
  html: command_block.html
  scenario: "NEXT"
  command: echo $TERM; ps ax | grep --color python
  description: "Display test : python processes"
-
  html: command_block.html
  scenario: "PART"
  command: "#SHUTDOWN"
  description: "Stop webint server"
-
  html: redirect_block.html
  scenario: "PART"
  description: "Open K-portal"
  url: "https://\"+window.location.hostname+\":9005"
-
  html: redirect_block.html
  scenario: "STOP"
  description: "Configuration screen"
  url: "/next?counter=10"

#10
- html: default.html
  scenario: "PART"
  command: "echo \"Mail is: $mail\""
  description: "Display command args"
-
  html: command_block.html
  scenario: "PART"
  command: echo "sudo su kportal -c 'kp_tool view_admins'"
  description: "List K-portal admins"
-
  html: default.html
  scenario: "PART"
  command: echo "sudo su kportal -c 'kp_tool -e $mail add_admins'"
  description: "Add K-portal admin"
-
  html: envvars_block.html
  scenario: "PART"
  command: "#SETVARS"
  allowed_vars:
    KP_SELF_CERT: ""
    KP_WEB_DNS: "localhost"
    KP_WEB_MAIL: ""
  description: "Set environment vars"
-
  html: command_block.html
  scenario: "PART"
  command: "echo -e \"one\ntwo\n3\""
  description: "echo -e \"one\ntwo\n3\""
-
  html: command_block.html
  scenario: "PART"
  command: ./test_long.sh
  description: "Long test"

#15
-
  html: command_block.html
  scenario: "PART"
  command: ./disp.sh
  description: "Display test"
-
  html: command_block.html
  scenario: "PART"
  command: "ps ax | grep webint"
  description: "Check that webint server is runnning"
-
  html: command_block.html
  scenario: "PART"
  command: "#SHUTDOWN"
  description: Shutdown webint server
-
  html: message_block.html
  scenario: "PART"
  description: "Message test"
-
  html: message_block.html
  scenario: "PART"
  description: "Message test"

#20
-
  html: message_block.html
  scenario: "PART"
  description: "Message test"
-
  html: message_block.html
  scenario: "PART"
  description: "Message test"
-
  html: redirect_block.html
  scenario: "STOP"
  description: "Open K-portal"
  url: "https://\"+window.location.hostname+\":9005"
