-
  html: envvars_block.html
  scenario: "NEXT"
  command: "#SETVARS"
  allowed_vars:
    KP_SELF_CERT: ""
    KP_WEB_DNS: "localhost"
    KP_WEB_MAIL: ""
  discription: "Set environment vars"
-
  html: command_block.html
  scenario: "NEXT"
  command: ./test_long.sh
  discription: "Long test"
-
  html: command_block.html
  scenario: "NEXT"
  command: env | grep "KP_"
  discription: "Check KP_* envvars"
-
  html: save_to_xml.html
  scenario: "NEXT"
  command: "#XML"
  filepath: ../config.xml
  discription: Edit kp_server configuration file
-
  html: command_block.html
  scenario: "PART"
  command: ./disp.sh
  discription: "Display test"
-
  html: command_block.html
  scenario: "NEXT"
  command: ./disp.sh
  discription: "Display test"
-
  html: command_block.html
  scenario: "STOP"
  command: "#SHUTDOWN"
  discription: "Stop webint server"
-
  html: command_block.html
  scenario: "PART"
  command: ls -l /etc/
  discription: "ls /etc"
-
  html: command_block.html
  scenario: "STOP"
  command: "#SHUTDOWN"
  discription: "Stop webint server"